### PR TITLE
Updated Rocket Show Startup Guide to 2.2

### PR DESCRIPTION
**Pull request by DavidOpgh**
Updated Appendix B a lot, added Backup/Restore. uploaded additional images. Other misc changes.

### CODE REVIEW

**Comment by moritzvieli** [comment]
Thanks! Great stuff! 🎉

**Comment by DavidOpgh** [comment]
You're welcome. First time using Markdown in Github. It took me a little longer to get the formatting the way I wanted it going back and forth between the editor and preview views. 

I'll be curious to see what kind of feedback I get from a new user.

**Comment by moritzvieli** [comment]
@DavidOpgh Just so you know: There are online markdown editors available (e.g. https://stackedit.io/app#) but they might not work well with the included images. Another way is to clone the repo locally and edit the Markdown for example with Visual Studio Code and a Markdown plugin.

**Comment by DavidOpgh** [comment]
OK - thanks for the info.

**Pull request merged**
